### ISSUE TITLE
Hard to score questions

### ISSUE THREAD

**Issue by AngainorDev** [manyoso/haltt4llm#1]
Hi,

I adapted the script and am running the tests on several alpaca loras.

Some answers do not always fit the choices and are counted as wrong, not because of hallucination but because the right answer was not in the choices, ex:

```
Question 31: Who wrote the musical 'The Phantom of the Opera'?
    A. Stephen Sondheim
    B. Lin-Manuel Miranda
    C. Elton John
    D. None of the above
    E. I don't know
Answer: The musical 'The Phantom of the Opera' was written by Andrew Lloyd Webber. (incorrect D.)
```

Whereas sometimes, it answers D. None of the above as intended.
```
Question 152: What type of architectural style is exemplified by the Parthenon in Greece?
    A. Gothic
    B. Romanesque
    C. Baroque
    D. None of the above
    E. I don't know
Answer: D. None of the above (correct)
```

I guess this is hard to id and still is meant to count as a wrong answer (did not stick to the multiple choice request)

**Comment by adtreat** [comment]
That's intended behavior. It should stick to picking one of the choices rather than providing its own answer.
